"""
demo.py - End-to-end demonstration of the five-stage zero-cost proxy framework
described in the manuscript.

Run from this directory:

    python demo.py --qubits 4 --n 30

The script executes all five framework stages on randomly sampled architectures
(no precomputed databases are required):

  Stage I   : Hardware-aware uniform sampling (HA-US). Candidate circuits are
              generated by data_prepare.decisions_generator under the
              hardware-compatible virtual gate set (HC-VGS) and the physical
              coupling map.
  Stage II  : Zero-cost proxy extraction. The 26-dimensional proxy features of
              every candidate are computed by
              quantum_api_v3.calculate_graph_proxies_ray.
  Stage III : Unsupervised latent sampling (protocol of
              the stratified-sampling notebook). A PCA basis of the proxy
              matrix is built, the latent space is partitioned into joint
              quadrants, and a stratified subset is selected with
              sample_from_bins.
  Stage IV  : Noise-aware architecture evaluation (protocol of
              the ground-truth evaluation notebook). The selected architectures
              are evaluated by VQCPipeline (classification) or VQEPipeline
              (VQE ground-state energy) with the clock-scheduled noise model
              on the mixed-state device to obtain ground-truth labels.
  Stage V   : Surrogate training and Top-K Gain validation. The XGBoost
              surrogate is trained on the labeled pairs produced by Stage IV
              and validated with compute_relative_topk_gain_auc
              (stage5_surrogate.py).

The demo evaluates a small subset for speed; in a full run, every architecture
selected in Stage III would be labeled by the Stage IV pipeline.
"""

import argparse
import os
import shelve
import tempfile

import matplotlib

matplotlib.use("Agg")

import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

from data_prepare import (
    NonlinearFeatureTransformer,
    compute_latent_boundaries,
    decisions_generator,
    get_bin_indices,
    sample_from_bins,
)
from quantum_api_v3 import calculate_graph_proxies_ray

# Real pool-construction configurations (identical to the manuscript):
#   4-qubit classification: x_num=(1,50), param=(1,40), ent=(1,40)
#   7-qubit VQE           : x_num=(0,0),  param=(1,100), ent=(1,30)
COUPLING_4Q = [[0, 1], [1, 2], [1, 3]]
COUPLING_7Q = [[0, 1], [1, 2], [1, 3], [3, 5], [5, 4], [5, 6]]
POOL_CONFIG = {
    4: {"x_num": (1, 50), "param_num_range": (1, 40), "ent_num_range": (1, 40), "coupling": COUPLING_4Q},
    7: {"x_num": (0, 0), "param_num_range": (1, 100), "ent_num_range": (1, 30), "coupling": COUPLING_7Q},
}

PROXY_COLUMNS = [
    "expressibility", "expressibility_embed", "mean_length", "width",
    "mean_encode_cent", "mean_trainable_cent", "data_dominance",
    "n_encoding", "n_trainable", "n_two_qubit_gates", "encoding_param_ratio",
    "redundancy_ratio", "encoding_entropy", "param_entropy", "global_entropy",
    "ent_entropy_universal", "ent_entropy_hardware", "ep_js_divergence",
    "st_mutual_info", "topological_center_diff", "path_alternation_rates",
    "trainability", "snip", "error_lightcone_vol", "lifespan_imbalance",
    "data_reinjection_index",
]

# Same configuration as the ground-truth evaluation notebook: the noise-aware
# pipeline uses the clock-scheduled injector with its default hardware
# parameters (heuristic type) on the mixed-state device.
NOISE_PARAM = {"type": "heuristic"}
DEV_NAME = "default.mixed"
DEVICE = "cuda"
BATCH_SIZE = 256

N_EVAL_CLS = 6   # number of selected architectures evaluated by Stage IV (classification)
N_EVAL_VQE = 3   # number of selected architectures evaluated by Stage IV (VQE)


def run_stage_iv(circuits, selected, qubits, seed, tmp_dir):
    """Evaluate the selected architectures with the Stage IV pipeline (real labels)."""
    import torch
    from torch.utils.data import TensorDataset
    from compute_metric import VQCPipeline, VQEPipeline
    from data_prepare import get_cluster_hamiltonian, make_shifted_circles

    n_eval = N_EVAL_CLS if qubits == 4 else N_EVAL_VQE
    n_eval = min(n_eval, len(selected))
    subset = [circuits[i] for i in selected[:n_eval]]

    if qubits == 4:
        X, y = make_shifted_circles(n_samples=300, random_state=seed)
        X = torch.tensor(X, dtype=torch.float32)
        y = torch.tensor(y, dtype=torch.long)

        def ds(a, b):
            return TensorDataset(X[a:b], y[a:b])

        pipe = VQCPipeline(
            ds(0, 200), ds(200, 250), ds(250, 300),
            n_qubits=qubits,
            input_dim=2,
            epochs=2,
            patience=2,
            min_epochs=1,
            dev_name=DEV_NAME,
            noise_param=NOISE_PARAM,
            device=DEVICE,
            batch_size=BATCH_SIZE,
            seed=seed,
            db_name=os.path.join(tmp_dir, "targets.db"),
        )
        labels = pipe.by_decisions(subset, mode="ray", disable_tqdm=True, shutdown_ray=False)
    else:
        # VQE target uses the cluster Hamiltonian in this release
        # (the notebook uses the TFIM Hamiltonian, which is not shipped).
        pipe = VQEPipeline(
            hamiltonian=get_cluster_hamiltonian(qubits),
            n_qubits=qubits,
            steps=20,
            patience=2,
            lr=0.01,
            dev_name=DEV_NAME,
            noise_param=NOISE_PARAM,
            device=DEVICE,
            seed=seed,
            db_name=os.path.join(tmp_dir, "vqe_targets.db"),
        )
        labels = pipe.by_decisions(subset, mode="ray", disable_tqdm=True, shutdown_ray=False)

    labels = [float(v) for v in labels]
    print(f"[Stage IV] Noise-aware ground truth "
          f"({'VQCPipeline' if qubits == 4 else 'VQEPipeline'}) on {len(subset)} selected architectures:")
    for i, idx in enumerate(selected[:n_eval]):
        print(f"            arch #{idx}: label = {labels[i]:.4f}")
    return selected[:n_eval], labels


def run_stage_v(proxies, eval_indices, labels, qubits, seed):
    """Train the XGBoost surrogate on the Stage IV labels and validate with Top-K Gain."""
    from stage5_surrogate import train_and_validate

    X_lab = proxies.iloc[eval_indices]
    y_lab = np.asarray(labels)
    if qubits == 7:  # VQE energies: larger is better
        y_lab = -y_lab

    model, metrics = train_and_validate(X_lab, y_lab, test_size=0.25, seed=seed)
    print(f"[Stage V] XGBoost surrogate trained on {len(eval_indices)} labeled pairs "
          f"(compute_relative_topk_gain_auc): "
          f"mean = {metrics['topk_gain_auc_mean']:.4f}, "
          f"max = {metrics['topk_gain_auc_max']:.4f}, "
          f"Spearman = {metrics['spearman']:.4f}")
    print("[Stage V] labels come from the Stage IV pipeline; the demo uses a small "
          "evaluated subset for speed.")


def main():
    parser = argparse.ArgumentParser(description="Five-stage zero-cost proxy framework demo")
    parser.add_argument("--qubits", type=int, choices=[4, 7], default=4)
    parser.add_argument("--n", type=int, default=30, help="number of sampled architectures")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    import ray

    ray.init(ignore_reinit_error=True, log_to_driver=False)
    try:
        # ---------- Stage I: hardware-aware uniform sampling ----------
        cfg = POOL_CONFIG[args.qubits]
        gen = decisions_generator(
            args.qubits,
            x_num=cfg["x_num"],
            param_num_range=cfg["param_num_range"],
            ent_num_range=cfg["ent_num_range"],
            allowed_gates=None,
            coupling_map=cfg["coupling"],
            num_circuits=args.n,
            seed=args.seed,
        )
        circuits = list(gen)[: args.n]
        print(f"[Stage I] Sampled {len(circuits)} candidate circuits on {args.qubits} qubits.")
        print(f"          gate counts: {[len(c) for c in circuits]}")

        # ---------- Stage II: zero-cost proxy extraction ----------
        with tempfile.TemporaryDirectory() as tmp:
            db_name = os.path.join(tmp, "pool.db")
            fps = calculate_graph_proxies_ray(
                iter(circuits),
                n_qubits=args.qubits,
                coupling_map=cfg["coupling"],
                db_name=db_name,
                disable_tqdm=True,
                seed=args.seed,
                num_cpus=1.0,
                num_gpus=0.05,
                total_circuits=len(circuits),
                shutdown_ray=False,
            )
            with shelve.open(db_name, flag="r") as d:
                rows = [{k: v for k, v in d[fp].items() if k != "graph"} for fp in fps]

        proxies = pd.DataFrame(rows)[PROXY_COLUMNS]
        print(f"[Stage II] Extracted {proxies.shape[0]} x {proxies.shape[1]} proxy features.")
        print(proxies.head().to_string(index=False))

        # ---------- Stage III: unsupervised latent sampling ----------
        trans = NonlinearFeatureTransformer()
        X = trans.fit_transform(proxies)
        pca_data = PCA(random_state=args.seed).fit_transform(X)
        boundaries = compute_latent_boundaries(pca_data, num_components=3, quantiles=[0.33, 0.66])
        bin_indices = get_bin_indices(pca_data, num_components=3, boundaries=boundaries)

        uniq, counts = np.unique(bin_indices, axis=0, return_counts=True)
        print(f"[Stage III] Latent space partitioned into {len(uniq)} non-empty joint quadrants.")
        for b, c in zip(uniq, counts):
            print(f"            bin {tuple(int(x) for x in b)}: {c} architectures")

        selected = sample_from_bins(
            bin_indices,
            total_samples=int(0.6 * len(proxies)),
            seed=args.seed,
            incremental=False,
            quiet=True,
        )
        print(f"[Stage III] Stratified subset selected: {len(selected)} architectures "
              f"({100.0 * len(selected) / len(proxies):.0f}% of the pool).")

        # ---------- Stage IV: noise-aware evaluation (pipeline, real labels, ray mode) ----------
        with tempfile.TemporaryDirectory() as tmp:
            eval_indices, labels = run_stage_iv(circuits, selected, args.qubits, args.seed, tmp)

        # ---------- Stage V: surrogate training + Top-K Gain validation ----------
        run_stage_v(proxies, eval_indices, labels, args.qubits, args.seed)

        print("\nDemo complete.")
    finally:
        ray.shutdown()


if __name__ == "__main__":
    main()
